### ISSUE TITLE
Connection errors when using Brave

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#498] opened 2020-04-02 14:11 UTC
It is different for different users. In some cases the metamask button is disabled even though MM is installed and connected to the right network. Some users can connect but see errors on the console and can't use the app.

**Comment by leolower** [comment] 2020-04-02 14:13
![image](https://user-images.githubusercontent.com/170611/78259376-0213e080-74d3-11ea-85a0-3eecb56ca1fb.png)
![image](https://user-images.githubusercontent.com/170611/78259396-0809c180-74d3-11ea-9218-ea9caa06d56c.png)

**Comment by fvictorio** [comment] 2020-04-20 13:34
I can't reproduce this. The only problem I noticed was if the wallet is not setup, but the browser itself lets you know and prompts you to do the setup. I think we should close this and open it again if it's reported again and we have proper reproduction steps.

**Comment by fvictorio** [comment] 2020-04-28 15:29
Still can't reproduce. Worked for me both with the embedded wallet and with MetaMask. To use MetaMask, I had to install it and then go to Settings and use it as default:

![image](https://user-images.githubusercontent.com/417134/80498756-832f8d80-8942-11ea-9fa8-7364d53e3595.png)

Closing for now. Please re-open if someone has detailed reproduction steps.

**Closed by fvictorio** 2020-04-28 15:29 UTC
