### ISSUE TITLE
Rename "Single Select" market to "Categorical" market

### ISSUE THREAD

**Issue by ZDEV001** [protofire/gnosis-conditional-exchange#609] opened 2020-04-24 05:38 UTC

**Comment by fvictorio** [comment] 2020-04-24 14:46
Duplicate of https://github.com/protofire/gnosis-conditional-exchange/issues/594 Should be fixed (but maybe not deployed yet). Please reopen if it isn't.

**Closed by fvictorio** 2020-04-24 14:46 UTC
